### ISSUE TITLE
Latvia and Estonia list

### ISSUE THREAD

**Issue by itstaticidle** [ElBozoII/PC-Retailer-List#3]
Some suggestions I have, fixing the list a bit and adding some links
## Estonia
Price Comparison: https://hv.ee/ *, https://hind.ee/

Stores: https://arvutitark.ee/, https://datagate.ee/, https://manguarvutid.ee/en/, https://www.rde.ee/, https://www.1a.ee/, https://www.itshop.ee/, https://kaup24.ee/, https://www.klick.ee/, https://onoff.ee/en/

Used marketplaces: https://okidoki.ee/, https://www.osta.ee/en

## Latvia
Price Comparison: https://salidzini.lv/ *, https://ceno.lv/en/, https://www.kurpirkt.lv/

Stores: https://maxtrade.lv/ *, https://m79.lv/ *, https://www.1a.lv/, https://rd.lv/, https://220.lv/, https://www.4games.pro/en/, https://balticdata.lv/en/, https://oreol.eu/, https://www.euronics.lv/en

Used marketplaces: https://www.ss.lv/en/, https://pp.lv/

> Changes:
**Estonia:**
Moved hind.ee and hinnavaatlus.ee (shortened to hv.ee) to Price Comparison
Added osta.ee to Used marketplaces (auction site for citizens, viewing for everyone)
**Latvia:**
Moved salidzini.lv to Price Comparison, added ceno.lv
Added m79.lv and euronics.lv to Stores, shortened rdveikals.lv to rd.lv
Added pp.lv to Used marketplaces

**Comment by ElBozoII** [comment]
yay free slave labor /s
thanks, also will probably consider all marketplaces as "used marketplaces" instead of retailers going forward
euronics will probably go under general retailers (europe) at the top
